FROM golang:1.18.3-stretch

RUN apt update && apt upgrade -y && \
  apt install -y git \
  make openssh-client

WORKDIR /app 

RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

CMD air